# Set up a development environment using the conda package manager
name: burocrata
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.13
  - pip
  - make
  # Run-time
  - click>=8.0.0,<9.0.0
  - tomli>=1.0.0,<3.0.0
  - pathspec>=0.10.1
  # Build
  - python-build
  - twine
  # Testing
  - pytest
  - pytest-cov
  - coverage
  # Linting and style
  - black
  - isort
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-functions
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-simplify
  - flake8-unused-arguments
  - pep8-naming
