# Linting and style checks with GitHub Actions
#
# NOTE: Pin actions to a specific commit to avoid having the authentication
# token stolen if the Action is compromised. See the comments and links here:
# https://github.com/pypa/gh-action-pypi-publish/issues/27
#
name: code-style

# Only build PRs and the main branch. Pushes to branches will only be built
# when a PR is opened.
on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

###############################################################################
jobs:
  check:
    name: check style and format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Collect requirements
        run: |
          echo "Install Dependente to capture dependencies:"
          python -m pip install dependente==0.3.0
          echo ""
          echo "Capturing run-time dependencies:"
          dependente --source install > requirements-full.txt
          echo ""
          echo "Capturing dependencies from:"
          for requirement in $REQUIREMENTS
          do
            echo "  $requirement"
            cat $requirement >> requirements-full.txt
          done
          echo ""
          echo "Collected dependencies:"
          cat requirements-full.txt

      - name: Get the pip cache folder
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Setup caching for pip packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('env/requirements-full.txt') }}

      - name: Install requirements
        run: python -m pip install -r env/requirements-full.txt

      - name: List installed packages
        run: python -m pip freeze

      # Need this to use Burocrata to check itself
      - name: Install the package in editable mode
        run: python -m pip install --no-deps --editable .

      - name: Check code style and format
        run: make check
